FROM python:3.6-slim-stretch

# Keep wheelhouse in an image (1: keep, 0: not)
ARG KEEPWHEELHOUSE="1"

ARG RUNTIME_DEPS="locales"
ARG CHARSET="UTF-8"
ARG LOCALE="ja_JP.UTF-8"
ARG TZ="Asia/Tokyo"
ARG APPUSER="bizmgt"
ARG APPDIR="/var/www/bizmgt"

RUN mkdir -p ${APPDIR}

COPY wheelhouse ${APPDIR}/wheelhouse
COPY requirements.txt ${APPDIR}/requirements.txt

ENV http_proxy={your_http_proxy}
ENV https_proxy={your_https_proxy}

RUN apt-get update && \
  # Install system dependencies
  apt-get install -y --no-install-recommends \
    ${RUNTIME_DEPS} && \
  # Setting the locale
  echo "${LOCALE} ${CHARSET}" >>/etc/locale.gen && \
  locale-gen && \
  # Setting the timezone
  ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
  echo ${TZ} > /etc/timezone && \
  # Create a non-root user for containers to run as
  useradd -M ${APPUSER} && \
  # Install python packages
  pip install \
    --no-index \
    --no-cache-dir \
    -f ${APPDIR}/wheelhouse \
    -r ${APPDIR}/requirements.txt && \
  # Cleanup
  rm -rf /var/lib/apt/lists/*

# Copy all files
COPY . ${APPDIR}

# Cleanup wheelhouse
RUN test "${KEEPWHEELHOUSE}" = "1" || \
    rm -rf ${APPDIR}/wheelhouse

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONPATH=${APPDIR}/bizmgt
ENV LANG=${LOCALE}
ENV TZ=${TZ}

WORKDIR ${APPDIR}
USER ${APPUSER}
